server: 
    port: 8081
spring: 
    cloud:
        config: 
            server:
                git: 
                    default-label: eureka
                    uri: https://github.com/SamDpg/microServices_Spring_tutorial
                    search-paths: config-data
    application:
        name: config-service